#pragma once

#include "Types.h"
#include "AutonomousScheduler.h"
#include "LearningSystem.h"
#include <memory>
#include <vector>
#include <unordered_map>
#include <string>
#include <atomic>
#include <mutex>
#include <chrono>

namespace NeuroForge {
    namespace Core {

        // Forward declarations
        class HypergraphBrain;

        /**
         * @brief Substrate-driven task generator for Milestone 7 autonomy
         * 
         * Generates autonomous tasks based on substrate state, intrinsic motivation,
         * and learning dynamics without external scaffolding.
         */
        class SubstrateTaskGenerator {
        public:
            /**
             * @brief Configuration for substrate task generation
             */
            struct Config {
                float curiosity_threshold{0.3f};           ///< Threshold for curiosity-driven tasks
                float uncertainty_threshold{0.4f};         ///< Threshold for uncertainty-based tasks
                float prediction_error_threshold{0.5f};    ///< Threshold for prediction error tasks
                float exploration_probability{0.2f};       ///< Probability of exploration tasks
                float consolidation_probability{0.1f};     ///< Probability of memory consolidation tasks
                std::uint32_t max_concurrent_tasks{5};     ///< Maximum concurrent autonomous tasks
                std::uint64_t task_generation_interval_ms{1000}; ///< Interval between task generation cycles
                bool enable_adaptive_goals{true};          ///< Enable adaptive goal generation
                bool enable_self_reflection{true};         ///< Enable autonomous self-reflection
                float performance_threshold{0.6f};         ///< Performance threshold for task success
            };

            /**
             * @brief Task generation context from substrate state
             */
            struct SubstrateContext {
                float global_activation{0.0f};             ///< Current global brain activation
                float learning_rate{0.0f};                 ///< Current learning rate
                float intrinsic_motivation{0.0f};          ///< Intrinsic motivation level
                float uncertainty_level{0.0f};             ///< Current uncertainty level
                float prediction_error{0.0f};              ///< Current prediction error
                std::vector<float> region_activations;     ///< Per-region activation levels
                std::unordered_map<std::string, float> performance_metrics; ///< Performance indicators
                std::uint64_t processing_cycles{0};        ///< Number of processing cycles
                std::chrono::steady_clock::time_point timestamp; ///< Context timestamp
            };

            /**
             * @brief Autonomous task types generated by substrate
             */
            enum class SubstrateTaskType {
                Exploration,        ///< Curiosity-driven exploration
                Consolidation,      ///< Memory consolidation
                Optimization,       ///< Performance optimization
                SelfReflection,     ///< Autonomous self-assessment
                PredictionImprovement, ///< Improve prediction accuracy
                NoveltySeek,        ///< Seek novel experiences
                SkillRefinement,    ///< Refine existing skills
                AdaptiveGoal        ///< Generate adaptive goals
            };

            /**
             * @brief Constructor
             */
            SubstrateTaskGenerator(std::shared_ptr<HypergraphBrain> brain,
                                 std::shared_ptr<AutonomousScheduler> scheduler,
                                 const Config& config);

            /**
             * @brief Initialize the task generator
             */
            bool initialize();

            /**
             * @brief Shutdown the task generator
             */
            void shutdown();

            /**
             * @brief Generate tasks based on current substrate state
             * @param delta_time Time elapsed since last generation cycle
             * @return Number of tasks generated
             */
            std::size_t generateTasks(float delta_time);

            /**
             * @brief Update substrate context from brain state
             */
            void updateSubstrateContext();

            /**
             * @brief Check if task generation should occur
             * @return True if tasks should be generated
             */
            bool shouldGenerateTasks() const;

            /**
             * @brief Generate exploration task based on curiosity
             * @return Task ID if generated, 0 otherwise
             */
            AutonomousTask::TaskID generateExplorationTask();

            /**
             * @brief Generate consolidation task for memory
             * @return Task ID if generated, 0 otherwise
             */
            AutonomousTask::TaskID generateConsolidationTask();

            /**
             * @brief Generate self-reflection task
             * @return Task ID if generated, 0 otherwise
             */
            AutonomousTask::TaskID generateSelfReflectionTask();

            /**
             * @brief Generate adaptive goal based on performance
             * @return Task ID if generated, 0 otherwise
             */
            AutonomousTask::TaskID generateAdaptiveGoal();

            /**
             * @brief Calculate intrinsic motivation from substrate state
             * @return Intrinsic motivation level [0.0, 1.0]
             */
            float calculateIntrinsicMotivation() const;

            /**
             * @brief Calculate uncertainty level from substrate dynamics
             * @return Uncertainty level [0.0, 1.0]
             */
            float calculateUncertaintyLevel() const;

            /**
             * @brief Calculate prediction error from learning system
             * @return Prediction error level [0.0, 1.0]
             */
            float calculatePredictionError() const;

            /**
             * @brief Evaluate task success and adapt generation parameters
             * @param task_id Completed task ID
             * @param success Whether task was successful
             * @param performance Performance metric [0.0, 1.0]
             */
            void evaluateTaskOutcome(AutonomousTask::TaskID task_id, bool success, float performance);

            /**
             * @brief Get current configuration
             */
            const Config& getConfig() const noexcept { return config_; }

            /**
             * @brief Update configuration
             */
            void setConfig(const Config& config) { config_ = config; }

            /**
             * @brief Get generation statistics
             */
            struct Statistics {
                std::uint64_t total_tasks_generated{0};
                std::uint64_t successful_tasks{0};
                std::uint64_t failed_tasks{0};
                float average_performance{0.0f};
                std::unordered_map<SubstrateTaskType, std::uint64_t> task_type_counts;
                std::chrono::steady_clock::time_point last_generation_time;
            };

            const Statistics& getStatistics() const noexcept { return stats_; }

            /**
             * @brief Enable or disable task generation
             * @param active True to enable task generation
             */
            void setActive(bool active);

            /**
             * @brief Check if task generation is active
             * @return True if task generation is active
             */
            bool isActive() const;

        private:
            std::shared_ptr<HypergraphBrain> brain_;
            std::shared_ptr<AutonomousScheduler> scheduler_;
            Config config_;
            Statistics stats_;
            SubstrateContext current_context_;
            
            std::atomic<bool> is_active_{false};
            std::atomic<std::uint64_t> generation_cycle_{0};
            mutable std::mutex context_mutex_;
            mutable std::mutex stats_mutex_;
            
            std::chrono::steady_clock::time_point last_generation_time_;
            std::unordered_map<AutonomousTask::TaskID, SubstrateTaskType> active_tasks_;

            /**
             * @brief Select task type based on substrate context
             */
            SubstrateTaskType selectTaskType() const;

            /**
             * @brief Create task name based on type and context
             */
            std::string generateTaskName(SubstrateTaskType type) const;

            /**
             * @brief Update adaptive parameters based on performance
             */
            void updateAdaptiveParameters();

            /**
             * @brief Check resource constraints for task generation
             */
            bool checkResourceConstraints() const;
        };

    } // namespace Core
} // namespace NeuroForge