// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: brainstate.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1004000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "neuroforge.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(8e272092801a1d3b);
CAPNP_DECLARE_SCHEMA(f949a6c38d5481c5);
CAPNP_DECLARE_SCHEMA(c9f47471b9fcf520);
CAPNP_DECLARE_SCHEMA(b5c88772c71cfb9f);

}  // namespace schemas
}  // namespace capnp

namespace NeuroForge {
namespace BrainState {

struct BrainStateFile {
  BrainStateFile() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(8e272092801a1d3b, 2, 4)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct PersistenceMetadata {
  PersistenceMetadata() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f949a6c38d5481c5, 7, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ExtendedState {
  ExtendedState() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(c9f47471b9fcf520, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct KeyValuePair {
  KeyValuePair() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(b5c88772c71cfb9f, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class BrainStateFile::Reader {
public:
  typedef BrainStateFile Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::int32_t getFileFormatVersion() const;

  inline  ::uint64_t getCreatedTimestamp() const;

  inline bool hasCreatedBy() const;
  inline  ::capnp::Text::Reader getCreatedBy() const;

  inline bool hasDescription() const;
  inline  ::capnp::Text::Reader getDescription() const;

  inline bool hasBrain() const;
  inline  ::NeuroForge::Schema::Brain::Reader getBrain() const;

  inline bool hasMetadata() const;
  inline  ::NeuroForge::BrainState::PersistenceMetadata::Reader getMetadata() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class BrainStateFile::Builder {
public:
  typedef BrainStateFile Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::int32_t getFileFormatVersion();
  inline void setFileFormatVersion( ::int32_t value);

  inline  ::uint64_t getCreatedTimestamp();
  inline void setCreatedTimestamp( ::uint64_t value);

  inline bool hasCreatedBy();
  inline  ::capnp::Text::Builder getCreatedBy();
  inline void setCreatedBy( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initCreatedBy(unsigned int size);
  inline void adoptCreatedBy(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownCreatedBy();

  inline bool hasDescription();
  inline  ::capnp::Text::Builder getDescription();
  inline void setDescription( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initDescription(unsigned int size);
  inline void adoptDescription(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownDescription();

  inline bool hasBrain();
  inline  ::NeuroForge::Schema::Brain::Builder getBrain();
  inline void setBrain( ::NeuroForge::Schema::Brain::Reader value);
  inline  ::NeuroForge::Schema::Brain::Builder initBrain();
  inline void adoptBrain(::capnp::Orphan< ::NeuroForge::Schema::Brain>&& value);
  inline ::capnp::Orphan< ::NeuroForge::Schema::Brain> disownBrain();

  inline bool hasMetadata();
  inline  ::NeuroForge::BrainState::PersistenceMetadata::Builder getMetadata();
  inline void setMetadata( ::NeuroForge::BrainState::PersistenceMetadata::Reader value);
  inline  ::NeuroForge::BrainState::PersistenceMetadata::Builder initMetadata();
  inline void adoptMetadata(::capnp::Orphan< ::NeuroForge::BrainState::PersistenceMetadata>&& value);
  inline ::capnp::Orphan< ::NeuroForge::BrainState::PersistenceMetadata> disownMetadata();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class BrainStateFile::Pipeline {
public:
  typedef BrainStateFile Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::NeuroForge::Schema::Brain::Pipeline getBrain();
  inline  ::NeuroForge::BrainState::PersistenceMetadata::Pipeline getMetadata();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class PersistenceMetadata::Reader {
public:
  typedef PersistenceMetadata Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getTotalNeurons() const;

  inline  ::uint64_t getTotalSynapses() const;

  inline  ::uint32_t getTotalRegions() const;

  inline float getAvgNeuronActivation() const;

  inline float getAvgSynapseWeight() const;

  inline float getProcessingFrequencyHz() const;

  inline float getLastUpdateDurationMs() const;

  inline float getMemoryUsageMB() const;

  inline  ::uint64_t getTotalPlasticUpdates() const;

  inline bool getLearningEnabled() const;

  inline bool hasNeuroforgeVersion() const;
  inline  ::capnp::Text::Reader getNeuroforgeVersion() const;

  inline bool hasSchemaVersion() const;
  inline  ::capnp::Text::Reader getSchemaVersion() const;

  inline bool hasDataChecksum() const;
  inline  ::capnp::Text::Reader getDataChecksum() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class PersistenceMetadata::Builder {
public:
  typedef PersistenceMetadata Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getTotalNeurons();
  inline void setTotalNeurons( ::uint64_t value);

  inline  ::uint64_t getTotalSynapses();
  inline void setTotalSynapses( ::uint64_t value);

  inline  ::uint32_t getTotalRegions();
  inline void setTotalRegions( ::uint32_t value);

  inline float getAvgNeuronActivation();
  inline void setAvgNeuronActivation(float value);

  inline float getAvgSynapseWeight();
  inline void setAvgSynapseWeight(float value);

  inline float getProcessingFrequencyHz();
  inline void setProcessingFrequencyHz(float value);

  inline float getLastUpdateDurationMs();
  inline void setLastUpdateDurationMs(float value);

  inline float getMemoryUsageMB();
  inline void setMemoryUsageMB(float value);

  inline  ::uint64_t getTotalPlasticUpdates();
  inline void setTotalPlasticUpdates( ::uint64_t value);

  inline bool getLearningEnabled();
  inline void setLearningEnabled(bool value);

  inline bool hasNeuroforgeVersion();
  inline  ::capnp::Text::Builder getNeuroforgeVersion();
  inline void setNeuroforgeVersion( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initNeuroforgeVersion(unsigned int size);
  inline void adoptNeuroforgeVersion(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownNeuroforgeVersion();

  inline bool hasSchemaVersion();
  inline  ::capnp::Text::Builder getSchemaVersion();
  inline void setSchemaVersion( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initSchemaVersion(unsigned int size);
  inline void adoptSchemaVersion(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownSchemaVersion();

  inline bool hasDataChecksum();
  inline  ::capnp::Text::Builder getDataChecksum();
  inline void setDataChecksum( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initDataChecksum(unsigned int size);
  inline void adoptDataChecksum(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownDataChecksum();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class PersistenceMetadata::Pipeline {
public:
  typedef PersistenceMetadata Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ExtendedState::Reader {
public:
  typedef ExtendedState Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasCustomData() const;
  inline  ::capnp::Data::Reader getCustomData() const;

  inline bool hasExtensionFields() const;
  inline  ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>::Reader getExtensionFields() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ExtendedState::Builder {
public:
  typedef ExtendedState Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasCustomData();
  inline  ::capnp::Data::Builder getCustomData();
  inline void setCustomData( ::capnp::Data::Reader value);
  inline  ::capnp::Data::Builder initCustomData(unsigned int size);
  inline void adoptCustomData(::capnp::Orphan< ::capnp::Data>&& value);
  inline ::capnp::Orphan< ::capnp::Data> disownCustomData();

  inline bool hasExtensionFields();
  inline  ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>::Builder getExtensionFields();
  inline void setExtensionFields( ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>::Builder initExtensionFields(unsigned int size);
  inline void adoptExtensionFields(::capnp::Orphan< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>> disownExtensionFields();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ExtendedState::Pipeline {
public:
  typedef ExtendedState Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class KeyValuePair::Reader {
public:
  typedef KeyValuePair Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasKey() const;
  inline  ::capnp::Text::Reader getKey() const;

  inline bool hasValue() const;
  inline  ::capnp::Text::Reader getValue() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class KeyValuePair::Builder {
public:
  typedef KeyValuePair Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasKey();
  inline  ::capnp::Text::Builder getKey();
  inline void setKey( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initKey(unsigned int size);
  inline void adoptKey(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownKey();

  inline bool hasValue();
  inline  ::capnp::Text::Builder getValue();
  inline void setValue( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initValue(unsigned int size);
  inline void adoptValue(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownValue();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class KeyValuePair::Pipeline {
public:
  typedef KeyValuePair Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::int32_t BrainStateFile::Reader::getFileFormatVersion() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, 1);
}

inline  ::int32_t BrainStateFile::Builder::getFileFormatVersion() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, 1);
}
inline void BrainStateFile::Builder::setFileFormatVersion( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value, 1);
}

inline  ::uint64_t BrainStateFile::Reader::getCreatedTimestamp() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t BrainStateFile::Builder::getCreatedTimestamp() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void BrainStateFile::Builder::setCreatedTimestamp( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool BrainStateFile::Reader::hasCreatedBy() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool BrainStateFile::Builder::hasCreatedBy() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader BrainStateFile::Reader::getCreatedBy() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS),
        ::capnp::schemas::bp_8e272092801a1d3b + 90, 10);
}
inline  ::capnp::Text::Builder BrainStateFile::Builder::getCreatedBy() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS),
        ::capnp::schemas::bp_8e272092801a1d3b + 90, 10);
}
inline void BrainStateFile::Builder::setCreatedBy( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder BrainStateFile::Builder::initCreatedBy(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void BrainStateFile::Builder::adoptCreatedBy(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> BrainStateFile::Builder::disownCreatedBy() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool BrainStateFile::Reader::hasDescription() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool BrainStateFile::Builder::hasDescription() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader BrainStateFile::Reader::getDescription() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder BrainStateFile::Builder::getDescription() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void BrainStateFile::Builder::setDescription( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder BrainStateFile::Builder::initDescription(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void BrainStateFile::Builder::adoptDescription(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> BrainStateFile::Builder::disownDescription() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool BrainStateFile::Reader::hasBrain() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool BrainStateFile::Builder::hasBrain() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::NeuroForge::Schema::Brain::Reader BrainStateFile::Reader::getBrain() const {
  return ::capnp::_::PointerHelpers< ::NeuroForge::Schema::Brain>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::NeuroForge::Schema::Brain::Builder BrainStateFile::Builder::getBrain() {
  return ::capnp::_::PointerHelpers< ::NeuroForge::Schema::Brain>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::NeuroForge::Schema::Brain::Pipeline BrainStateFile::Pipeline::getBrain() {
  return  ::NeuroForge::Schema::Brain::Pipeline(_typeless.getPointerField(2));
}
#endif  // !CAPNP_LITE
inline void BrainStateFile::Builder::setBrain( ::NeuroForge::Schema::Brain::Reader value) {
  ::capnp::_::PointerHelpers< ::NeuroForge::Schema::Brain>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::NeuroForge::Schema::Brain::Builder BrainStateFile::Builder::initBrain() {
  return ::capnp::_::PointerHelpers< ::NeuroForge::Schema::Brain>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void BrainStateFile::Builder::adoptBrain(
    ::capnp::Orphan< ::NeuroForge::Schema::Brain>&& value) {
  ::capnp::_::PointerHelpers< ::NeuroForge::Schema::Brain>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::NeuroForge::Schema::Brain> BrainStateFile::Builder::disownBrain() {
  return ::capnp::_::PointerHelpers< ::NeuroForge::Schema::Brain>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool BrainStateFile::Reader::hasMetadata() const {
  return !_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline bool BrainStateFile::Builder::hasMetadata() {
  return !_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline  ::NeuroForge::BrainState::PersistenceMetadata::Reader BrainStateFile::Reader::getMetadata() const {
  return ::capnp::_::PointerHelpers< ::NeuroForge::BrainState::PersistenceMetadata>::get(_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline  ::NeuroForge::BrainState::PersistenceMetadata::Builder BrainStateFile::Builder::getMetadata() {
  return ::capnp::_::PointerHelpers< ::NeuroForge::BrainState::PersistenceMetadata>::get(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::NeuroForge::BrainState::PersistenceMetadata::Pipeline BrainStateFile::Pipeline::getMetadata() {
  return  ::NeuroForge::BrainState::PersistenceMetadata::Pipeline(_typeless.getPointerField(3));
}
#endif  // !CAPNP_LITE
inline void BrainStateFile::Builder::setMetadata( ::NeuroForge::BrainState::PersistenceMetadata::Reader value) {
  ::capnp::_::PointerHelpers< ::NeuroForge::BrainState::PersistenceMetadata>::set(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), value);
}
inline  ::NeuroForge::BrainState::PersistenceMetadata::Builder BrainStateFile::Builder::initMetadata() {
  return ::capnp::_::PointerHelpers< ::NeuroForge::BrainState::PersistenceMetadata>::init(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline void BrainStateFile::Builder::adoptMetadata(
    ::capnp::Orphan< ::NeuroForge::BrainState::PersistenceMetadata>&& value) {
  ::capnp::_::PointerHelpers< ::NeuroForge::BrainState::PersistenceMetadata>::adopt(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::NeuroForge::BrainState::PersistenceMetadata> BrainStateFile::Builder::disownMetadata() {
  return ::capnp::_::PointerHelpers< ::NeuroForge::BrainState::PersistenceMetadata>::disown(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}

inline  ::uint64_t PersistenceMetadata::Reader::getTotalNeurons() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t PersistenceMetadata::Builder::getTotalNeurons() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setTotalNeurons( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t PersistenceMetadata::Reader::getTotalSynapses() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t PersistenceMetadata::Builder::getTotalSynapses() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setTotalSynapses( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t PersistenceMetadata::Reader::getTotalRegions() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t PersistenceMetadata::Builder::getTotalRegions() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setTotalRegions( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS, value);
}

inline float PersistenceMetadata::Reader::getAvgNeuronActivation() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}

inline float PersistenceMetadata::Builder::getAvgNeuronActivation() {
  return _builder.getDataField<float>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setAvgNeuronActivation(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS, value);
}

inline float PersistenceMetadata::Reader::getAvgSynapseWeight() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}

inline float PersistenceMetadata::Builder::getAvgSynapseWeight() {
  return _builder.getDataField<float>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setAvgSynapseWeight(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS, value);
}

inline float PersistenceMetadata::Reader::getProcessingFrequencyHz() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<7>() * ::capnp::ELEMENTS);
}

inline float PersistenceMetadata::Builder::getProcessingFrequencyHz() {
  return _builder.getDataField<float>(
      ::capnp::bounded<7>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setProcessingFrequencyHz(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<7>() * ::capnp::ELEMENTS, value);
}

inline float PersistenceMetadata::Reader::getLastUpdateDurationMs() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}

inline float PersistenceMetadata::Builder::getLastUpdateDurationMs() {
  return _builder.getDataField<float>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setLastUpdateDurationMs(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS, value);
}

inline float PersistenceMetadata::Reader::getMemoryUsageMB() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<9>() * ::capnp::ELEMENTS);
}

inline float PersistenceMetadata::Builder::getMemoryUsageMB() {
  return _builder.getDataField<float>(
      ::capnp::bounded<9>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setMemoryUsageMB(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<9>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t PersistenceMetadata::Reader::getTotalPlasticUpdates() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t PersistenceMetadata::Builder::getTotalPlasticUpdates() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setTotalPlasticUpdates( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS, value);
}

inline bool PersistenceMetadata::Reader::getLearningEnabled() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<384>() * ::capnp::ELEMENTS);
}

inline bool PersistenceMetadata::Builder::getLearningEnabled() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<384>() * ::capnp::ELEMENTS);
}
inline void PersistenceMetadata::Builder::setLearningEnabled(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<384>() * ::capnp::ELEMENTS, value);
}

inline bool PersistenceMetadata::Reader::hasNeuroforgeVersion() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool PersistenceMetadata::Builder::hasNeuroforgeVersion() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader PersistenceMetadata::Reader::getNeuroforgeVersion() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder PersistenceMetadata::Builder::getNeuroforgeVersion() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void PersistenceMetadata::Builder::setNeuroforgeVersion( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder PersistenceMetadata::Builder::initNeuroforgeVersion(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void PersistenceMetadata::Builder::adoptNeuroforgeVersion(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> PersistenceMetadata::Builder::disownNeuroforgeVersion() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool PersistenceMetadata::Reader::hasSchemaVersion() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool PersistenceMetadata::Builder::hasSchemaVersion() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader PersistenceMetadata::Reader::getSchemaVersion() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder PersistenceMetadata::Builder::getSchemaVersion() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void PersistenceMetadata::Builder::setSchemaVersion( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder PersistenceMetadata::Builder::initSchemaVersion(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void PersistenceMetadata::Builder::adoptSchemaVersion(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> PersistenceMetadata::Builder::disownSchemaVersion() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool PersistenceMetadata::Reader::hasDataChecksum() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool PersistenceMetadata::Builder::hasDataChecksum() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader PersistenceMetadata::Reader::getDataChecksum() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder PersistenceMetadata::Builder::getDataChecksum() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void PersistenceMetadata::Builder::setDataChecksum( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder PersistenceMetadata::Builder::initDataChecksum(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void PersistenceMetadata::Builder::adoptDataChecksum(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> PersistenceMetadata::Builder::disownDataChecksum() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool ExtendedState::Reader::hasCustomData() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ExtendedState::Builder::hasCustomData() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Data::Reader ExtendedState::Reader::getCustomData() const {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Data::Builder ExtendedState::Builder::getCustomData() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ExtendedState::Builder::setCustomData( ::capnp::Data::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Data::Builder ExtendedState::Builder::initCustomData(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void ExtendedState::Builder::adoptCustomData(
    ::capnp::Orphan< ::capnp::Data>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Data> ExtendedState::Builder::disownCustomData() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool ExtendedState::Reader::hasExtensionFields() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool ExtendedState::Builder::hasExtensionFields() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>::Reader ExtendedState::Reader::getExtensionFields() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>::Builder ExtendedState::Builder::getExtensionFields() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void ExtendedState::Builder::setExtensionFields( ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>::Builder ExtendedState::Builder::initExtensionFields(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void ExtendedState::Builder::adoptExtensionFields(
    ::capnp::Orphan< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>> ExtendedState::Builder::disownExtensionFields() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::BrainState::KeyValuePair,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool KeyValuePair::Reader::hasKey() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool KeyValuePair::Builder::hasKey() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader KeyValuePair::Reader::getKey() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder KeyValuePair::Builder::getKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void KeyValuePair::Builder::setKey( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder KeyValuePair::Builder::initKey(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void KeyValuePair::Builder::adoptKey(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> KeyValuePair::Builder::disownKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool KeyValuePair::Reader::hasValue() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool KeyValuePair::Builder::hasValue() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader KeyValuePair::Reader::getValue() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder KeyValuePair::Builder::getValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void KeyValuePair::Builder::setValue( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder KeyValuePair::Builder::initValue(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void KeyValuePair::Builder::adoptValue(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> KeyValuePair::Builder::disownValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

}  // namespace
}  // namespace

CAPNP_END_HEADER

