// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: neuroforge.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1002000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(da4a32e08935d25e);
enum class SynapseType_da4a32e08935d25e: uint16_t {
  EXCITATORY,
  INHIBITORY,
  MODULATORY,
};
CAPNP_DECLARE_ENUM(SynapseType, da4a32e08935d25e);
CAPNP_DECLARE_SCHEMA(d34f9e3ec81de153);
enum class PlasticityRule_d34f9e3ec81de153: uint16_t {
  NONE,
  HEBBIAN,
  STDP,
  BCM,
  OJA,
};
CAPNP_DECLARE_ENUM(PlasticityRule, d34f9e3ec81de153);
CAPNP_DECLARE_SCHEMA(8137d410c2694e6d);
enum class NeuronState_8137d410c2694e6d: uint16_t {
  INACTIVE,
  ACTIVE,
  INHIBITED,
  REFRACTORY,
};
CAPNP_DECLARE_ENUM(NeuronState, 8137d410c2694e6d);
CAPNP_DECLARE_SCHEMA(c7c2fdaae2437aa1);
enum class RegionType_c7c2fdaae2437aa1: uint16_t {
  CORTICAL,
  SUBCORTICAL,
  BRAINSTEM,
  SPECIAL,
  CUSTOM,
};
CAPNP_DECLARE_ENUM(RegionType, c7c2fdaae2437aa1);
CAPNP_DECLARE_SCHEMA(9dbad146b4c8c463);
enum class ActivationPattern_9dbad146b4c8c463: uint16_t {
  SYNCHRONOUS,
  ASYNCHRONOUS,
  LAYERED,
  COMPETITIVE,
  OSCILLATORY,
};
CAPNP_DECLARE_ENUM(ActivationPattern, 9dbad146b4c8c463);
CAPNP_DECLARE_SCHEMA(ade532373a148f04);
enum class ProcessingMode_ade532373a148f04: uint16_t {
  SEQUENTIAL,
  PARALLEL,
  HIERARCHICAL,
  CUSTOM,
};
CAPNP_DECLARE_ENUM(ProcessingMode, ade532373a148f04);
CAPNP_DECLARE_SCHEMA(c60207e4f328fc6d);
enum class BrainState_c60207e4f328fc6d: uint16_t {
  UNINITIALIZED,
  INITIALIZING,
  RUNNING,
  PAUSED,
  RESETTING,
  SHUTDOWN,
};
CAPNP_DECLARE_ENUM(BrainState, c60207e4f328fc6d);
CAPNP_DECLARE_SCHEMA(b64aa132fce8ea32);
CAPNP_DECLARE_SCHEMA(dd4e945cd615ca85);
CAPNP_DECLARE_SCHEMA(a718bb452ec16709);
CAPNP_DECLARE_SCHEMA(8537d575bf51d6d2);
CAPNP_DECLARE_SCHEMA(88efb6ef380856c0);

}  // namespace schemas
}  // namespace capnp

namespace NeuroForge {
namespace Schema {

typedef ::capnp::schemas::SynapseType_da4a32e08935d25e SynapseType;

typedef ::capnp::schemas::PlasticityRule_d34f9e3ec81de153 PlasticityRule;

typedef ::capnp::schemas::NeuronState_8137d410c2694e6d NeuronState;

typedef ::capnp::schemas::RegionType_c7c2fdaae2437aa1 RegionType;

typedef ::capnp::schemas::ActivationPattern_9dbad146b4c8c463 ActivationPattern;

typedef ::capnp::schemas::ProcessingMode_ade532373a148f04 ProcessingMode;

typedef ::capnp::schemas::BrainState_c60207e4f328fc6d BrainState;

struct Neuron {
  Neuron() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(b64aa132fce8ea32, 6, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Synapse {
  Synapse() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(dd4e945cd615ca85, 10, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct RegionNameEntry {
  RegionNameEntry() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a718bb452ec16709, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Region {
  Region() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(8537d575bf51d6d2, 3, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Brain {
  Brain() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(88efb6ef380856c0, 3, 4)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Neuron::Reader {
public:
  typedef Neuron Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getId() const;

  inline float getActivation() const;

  inline  ::NeuroForge::Schema::NeuronState getState() const;

  inline float getThreshold() const;

  inline float getDecayRate() const;

  inline float getRefractoryTimer() const;

  inline float getRefractoryPeriod() const;

  inline  ::uint64_t getFireCount() const;

  inline  ::uint64_t getProcessCount() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Neuron::Builder {
public:
  typedef Neuron Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getId();
  inline void setId( ::uint64_t value);

  inline float getActivation();
  inline void setActivation(float value);

  inline  ::NeuroForge::Schema::NeuronState getState();
  inline void setState( ::NeuroForge::Schema::NeuronState value);

  inline float getThreshold();
  inline void setThreshold(float value);

  inline float getDecayRate();
  inline void setDecayRate(float value);

  inline float getRefractoryTimer();
  inline void setRefractoryTimer(float value);

  inline float getRefractoryPeriod();
  inline void setRefractoryPeriod(float value);

  inline  ::uint64_t getFireCount();
  inline void setFireCount( ::uint64_t value);

  inline  ::uint64_t getProcessCount();
  inline void setProcessCount( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Neuron::Pipeline {
public:
  typedef Neuron Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Synapse::Reader {
public:
  typedef Synapse Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getId() const;

  inline  ::uint32_t getSourceRegionId() const;

  inline  ::uint32_t getTargetRegionId() const;

  inline  ::uint64_t getSourceNeuronId() const;

  inline  ::uint64_t getTargetNeuronId() const;

  inline float getWeight() const;

  inline float getInitialWeight() const;

  inline  ::NeuroForge::Schema::SynapseType getType() const;

  inline  ::NeuroForge::Schema::PlasticityRule getPlasticityRule() const;

  inline float getLearningRate() const;

  inline float getDelayMs() const;

  inline float getMinWeight() const;

  inline float getMaxWeight() const;

  inline  ::uint64_t getSignalCount() const;

  inline  ::uint64_t getUpdateCount() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Synapse::Builder {
public:
  typedef Synapse Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getId();
  inline void setId( ::uint64_t value);

  inline  ::uint32_t getSourceRegionId();
  inline void setSourceRegionId( ::uint32_t value);

  inline  ::uint32_t getTargetRegionId();
  inline void setTargetRegionId( ::uint32_t value);

  inline  ::uint64_t getSourceNeuronId();
  inline void setSourceNeuronId( ::uint64_t value);

  inline  ::uint64_t getTargetNeuronId();
  inline void setTargetNeuronId( ::uint64_t value);

  inline float getWeight();
  inline void setWeight(float value);

  inline float getInitialWeight();
  inline void setInitialWeight(float value);

  inline  ::NeuroForge::Schema::SynapseType getType();
  inline void setType( ::NeuroForge::Schema::SynapseType value);

  inline  ::NeuroForge::Schema::PlasticityRule getPlasticityRule();
  inline void setPlasticityRule( ::NeuroForge::Schema::PlasticityRule value);

  inline float getLearningRate();
  inline void setLearningRate(float value);

  inline float getDelayMs();
  inline void setDelayMs(float value);

  inline float getMinWeight();
  inline void setMinWeight(float value);

  inline float getMaxWeight();
  inline void setMaxWeight(float value);

  inline  ::uint64_t getSignalCount();
  inline void setSignalCount( ::uint64_t value);

  inline  ::uint64_t getUpdateCount();
  inline void setUpdateCount( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Synapse::Pipeline {
public:
  typedef Synapse Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class RegionNameEntry::Reader {
public:
  typedef RegionNameEntry Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint32_t getId() const;

  inline bool hasName() const;
  inline  ::capnp::Text::Reader getName() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class RegionNameEntry::Builder {
public:
  typedef RegionNameEntry Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint32_t getId();
  inline void setId( ::uint32_t value);

  inline bool hasName();
  inline  ::capnp::Text::Builder getName();
  inline void setName( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initName(unsigned int size);
  inline void adoptName(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownName();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class RegionNameEntry::Pipeline {
public:
  typedef RegionNameEntry Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Region::Reader {
public:
  typedef Region Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint32_t getId() const;

  inline bool hasName() const;
  inline  ::capnp::Text::Reader getName() const;

  inline  ::NeuroForge::Schema::RegionType getType() const;

  inline  ::NeuroForge::Schema::ActivationPattern getActivationPattern() const;

  inline bool hasNeurons() const;
  inline  ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>::Reader getNeurons() const;

  inline bool hasInternalSynapses() const;
  inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Reader getInternalSynapses() const;

  inline bool getIsActive() const;

  inline float getGlobalActivation() const;

  inline  ::uint64_t getProcessingCycles() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Region::Builder {
public:
  typedef Region Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint32_t getId();
  inline void setId( ::uint32_t value);

  inline bool hasName();
  inline  ::capnp::Text::Builder getName();
  inline void setName( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initName(unsigned int size);
  inline void adoptName(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownName();

  inline  ::NeuroForge::Schema::RegionType getType();
  inline void setType( ::NeuroForge::Schema::RegionType value);

  inline  ::NeuroForge::Schema::ActivationPattern getActivationPattern();
  inline void setActivationPattern( ::NeuroForge::Schema::ActivationPattern value);

  inline bool hasNeurons();
  inline  ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>::Builder getNeurons();
  inline void setNeurons( ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>::Builder initNeurons(unsigned int size);
  inline void adoptNeurons(::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>> disownNeurons();

  inline bool hasInternalSynapses();
  inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Builder getInternalSynapses();
  inline void setInternalSynapses( ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Builder initInternalSynapses(unsigned int size);
  inline void adoptInternalSynapses(::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>> disownInternalSynapses();

  inline bool getIsActive();
  inline void setIsActive(bool value);

  inline float getGlobalActivation();
  inline void setGlobalActivation(float value);

  inline  ::uint64_t getProcessingCycles();
  inline void setProcessingCycles( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Region::Pipeline {
public:
  typedef Region Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Brain::Reader {
public:
  typedef Brain Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::int32_t getFormatVersion() const;

  inline  ::NeuroForge::Schema::ProcessingMode getProcessingMode() const;

  inline  ::NeuroForge::Schema::BrainState getBrainState() const;

  inline float getTargetFrequency() const;

  inline  ::uint64_t getProcessingCycles() const;

  inline bool hasRegions() const;
  inline  ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>::Reader getRegions() const;

  inline bool hasGlobalSynapses() const;
  inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Reader getGlobalSynapses() const;

  inline bool hasRegionNames() const;
  inline  ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>::Reader getRegionNames() const;

  inline bool hasCustomUpdateOrder() const;
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader getCustomUpdateOrder() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Brain::Builder {
public:
  typedef Brain Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::int32_t getFormatVersion();
  inline void setFormatVersion( ::int32_t value);

  inline  ::NeuroForge::Schema::ProcessingMode getProcessingMode();
  inline void setProcessingMode( ::NeuroForge::Schema::ProcessingMode value);

  inline  ::NeuroForge::Schema::BrainState getBrainState();
  inline void setBrainState( ::NeuroForge::Schema::BrainState value);

  inline float getTargetFrequency();
  inline void setTargetFrequency(float value);

  inline  ::uint64_t getProcessingCycles();
  inline void setProcessingCycles( ::uint64_t value);

  inline bool hasRegions();
  inline  ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>::Builder getRegions();
  inline void setRegions( ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>::Builder initRegions(unsigned int size);
  inline void adoptRegions(::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>> disownRegions();

  inline bool hasGlobalSynapses();
  inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Builder getGlobalSynapses();
  inline void setGlobalSynapses( ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Builder initGlobalSynapses(unsigned int size);
  inline void adoptGlobalSynapses(::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>> disownGlobalSynapses();

  inline bool hasRegionNames();
  inline  ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>::Builder getRegionNames();
  inline void setRegionNames( ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>::Builder initRegionNames(unsigned int size);
  inline void adoptRegionNames(::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>> disownRegionNames();

  inline bool hasCustomUpdateOrder();
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder getCustomUpdateOrder();
  inline void setCustomUpdateOrder( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setCustomUpdateOrder(::kj::ArrayPtr<const  ::uint32_t> value);
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder initCustomUpdateOrder(unsigned int size);
  inline void adoptCustomUpdateOrder(::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> disownCustomUpdateOrder();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Brain::Pipeline {
public:
  typedef Brain Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::uint64_t Neuron::Reader::getId() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Neuron::Builder::getId() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Neuron::Builder::setId( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline float Neuron::Reader::getActivation() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline float Neuron::Builder::getActivation() {
  return _builder.getDataField<float>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Neuron::Builder::setActivation(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::NeuroForge::Schema::NeuronState Neuron::Reader::getState() const {
  return _reader.getDataField< ::NeuroForge::Schema::NeuronState>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}

inline  ::NeuroForge::Schema::NeuronState Neuron::Builder::getState() {
  return _builder.getDataField< ::NeuroForge::Schema::NeuronState>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}
inline void Neuron::Builder::setState( ::NeuroForge::Schema::NeuronState value) {
  _builder.setDataField< ::NeuroForge::Schema::NeuronState>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS, value);
}

inline float Neuron::Reader::getThreshold() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}

inline float Neuron::Builder::getThreshold() {
  return _builder.getDataField<float>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}
inline void Neuron::Builder::setThreshold(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS, value);
}

inline float Neuron::Reader::getDecayRate() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}

inline float Neuron::Builder::getDecayRate() {
  return _builder.getDataField<float>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}
inline void Neuron::Builder::setDecayRate(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS, value);
}

inline float Neuron::Reader::getRefractoryTimer() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}

inline float Neuron::Builder::getRefractoryTimer() {
  return _builder.getDataField<float>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}
inline void Neuron::Builder::setRefractoryTimer(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS, value);
}

inline float Neuron::Reader::getRefractoryPeriod() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<7>() * ::capnp::ELEMENTS);
}

inline float Neuron::Builder::getRefractoryPeriod() {
  return _builder.getDataField<float>(
      ::capnp::bounded<7>() * ::capnp::ELEMENTS);
}
inline void Neuron::Builder::setRefractoryPeriod(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<7>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t Neuron::Reader::getFireCount() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Neuron::Builder::getFireCount() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}
inline void Neuron::Builder::setFireCount( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t Neuron::Reader::getProcessCount() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Neuron::Builder::getProcessCount() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}
inline void Neuron::Builder::setProcessCount( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t Synapse::Reader::getId() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Synapse::Builder::getId() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setId( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t Synapse::Reader::getSourceRegionId() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Synapse::Builder::getSourceRegionId() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setSourceRegionId( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t Synapse::Reader::getTargetRegionId() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Synapse::Builder::getTargetRegionId() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setTargetRegionId( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t Synapse::Reader::getSourceNeuronId() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Synapse::Builder::getSourceNeuronId() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setSourceNeuronId( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t Synapse::Reader::getTargetNeuronId() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Synapse::Builder::getTargetNeuronId() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setTargetNeuronId( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline float Synapse::Reader::getWeight() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}

inline float Synapse::Builder::getWeight() {
  return _builder.getDataField<float>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setWeight(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS, value);
}

inline float Synapse::Reader::getInitialWeight() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<9>() * ::capnp::ELEMENTS);
}

inline float Synapse::Builder::getInitialWeight() {
  return _builder.getDataField<float>(
      ::capnp::bounded<9>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setInitialWeight(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<9>() * ::capnp::ELEMENTS, value);
}

inline  ::NeuroForge::Schema::SynapseType Synapse::Reader::getType() const {
  return _reader.getDataField< ::NeuroForge::Schema::SynapseType>(
      ::capnp::bounded<20>() * ::capnp::ELEMENTS);
}

inline  ::NeuroForge::Schema::SynapseType Synapse::Builder::getType() {
  return _builder.getDataField< ::NeuroForge::Schema::SynapseType>(
      ::capnp::bounded<20>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setType( ::NeuroForge::Schema::SynapseType value) {
  _builder.setDataField< ::NeuroForge::Schema::SynapseType>(
      ::capnp::bounded<20>() * ::capnp::ELEMENTS, value);
}

inline  ::NeuroForge::Schema::PlasticityRule Synapse::Reader::getPlasticityRule() const {
  return _reader.getDataField< ::NeuroForge::Schema::PlasticityRule>(
      ::capnp::bounded<21>() * ::capnp::ELEMENTS);
}

inline  ::NeuroForge::Schema::PlasticityRule Synapse::Builder::getPlasticityRule() {
  return _builder.getDataField< ::NeuroForge::Schema::PlasticityRule>(
      ::capnp::bounded<21>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setPlasticityRule( ::NeuroForge::Schema::PlasticityRule value) {
  _builder.setDataField< ::NeuroForge::Schema::PlasticityRule>(
      ::capnp::bounded<21>() * ::capnp::ELEMENTS, value);
}

inline float Synapse::Reader::getLearningRate() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<11>() * ::capnp::ELEMENTS);
}

inline float Synapse::Builder::getLearningRate() {
  return _builder.getDataField<float>(
      ::capnp::bounded<11>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setLearningRate(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<11>() * ::capnp::ELEMENTS, value);
}

inline float Synapse::Reader::getDelayMs() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<12>() * ::capnp::ELEMENTS);
}

inline float Synapse::Builder::getDelayMs() {
  return _builder.getDataField<float>(
      ::capnp::bounded<12>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setDelayMs(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<12>() * ::capnp::ELEMENTS, value);
}

inline float Synapse::Reader::getMinWeight() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<13>() * ::capnp::ELEMENTS);
}

inline float Synapse::Builder::getMinWeight() {
  return _builder.getDataField<float>(
      ::capnp::bounded<13>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setMinWeight(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<13>() * ::capnp::ELEMENTS, value);
}

inline float Synapse::Reader::getMaxWeight() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS);
}

inline float Synapse::Builder::getMaxWeight() {
  return _builder.getDataField<float>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setMaxWeight(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t Synapse::Reader::getSignalCount() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Synapse::Builder::getSignalCount() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setSignalCount( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t Synapse::Reader::getUpdateCount() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<9>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Synapse::Builder::getUpdateCount() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<9>() * ::capnp::ELEMENTS);
}
inline void Synapse::Builder::setUpdateCount( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<9>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t RegionNameEntry::Reader::getId() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t RegionNameEntry::Builder::getId() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void RegionNameEntry::Builder::setId( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool RegionNameEntry::Reader::hasName() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool RegionNameEntry::Builder::hasName() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader RegionNameEntry::Reader::getName() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder RegionNameEntry::Builder::getName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void RegionNameEntry::Builder::setName( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder RegionNameEntry::Builder::initName(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void RegionNameEntry::Builder::adoptName(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> RegionNameEntry::Builder::disownName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::uint32_t Region::Reader::getId() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Region::Builder::getId() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Region::Builder::setId( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Region::Reader::hasName() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Region::Builder::hasName() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader Region::Reader::getName() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder Region::Builder::getName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Region::Builder::setName( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder Region::Builder::initName(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Region::Builder::adoptName(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> Region::Builder::disownName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::NeuroForge::Schema::RegionType Region::Reader::getType() const {
  return _reader.getDataField< ::NeuroForge::Schema::RegionType>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::NeuroForge::Schema::RegionType Region::Builder::getType() {
  return _builder.getDataField< ::NeuroForge::Schema::RegionType>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Region::Builder::setType( ::NeuroForge::Schema::RegionType value) {
  _builder.setDataField< ::NeuroForge::Schema::RegionType>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::NeuroForge::Schema::ActivationPattern Region::Reader::getActivationPattern() const {
  return _reader.getDataField< ::NeuroForge::Schema::ActivationPattern>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline  ::NeuroForge::Schema::ActivationPattern Region::Builder::getActivationPattern() {
  return _builder.getDataField< ::NeuroForge::Schema::ActivationPattern>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void Region::Builder::setActivationPattern( ::NeuroForge::Schema::ActivationPattern value) {
  _builder.setDataField< ::NeuroForge::Schema::ActivationPattern>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline bool Region::Reader::hasNeurons() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Region::Builder::hasNeurons() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>::Reader Region::Reader::getNeurons() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>::Builder Region::Builder::getNeurons() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Region::Builder::setNeurons( ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>::Builder Region::Builder::initNeurons(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void Region::Builder::adoptNeurons(
    ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>> Region::Builder::disownNeurons() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Neuron,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool Region::Reader::hasInternalSynapses() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool Region::Builder::hasInternalSynapses() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Reader Region::Reader::getInternalSynapses() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Builder Region::Builder::getInternalSynapses() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void Region::Builder::setInternalSynapses( ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Builder Region::Builder::initInternalSynapses(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void Region::Builder::adoptInternalSynapses(
    ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>> Region::Builder::disownInternalSynapses() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool Region::Reader::getIsActive() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<64>() * ::capnp::ELEMENTS);
}

inline bool Region::Builder::getIsActive() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<64>() * ::capnp::ELEMENTS);
}
inline void Region::Builder::setIsActive(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<64>() * ::capnp::ELEMENTS, value);
}

inline float Region::Reader::getGlobalActivation() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline float Region::Builder::getGlobalActivation() {
  return _builder.getDataField<float>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void Region::Builder::setGlobalActivation(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t Region::Reader::getProcessingCycles() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Region::Builder::getProcessingCycles() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Region::Builder::setProcessingCycles( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::int32_t Brain::Reader::getFormatVersion() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::int32_t Brain::Builder::getFormatVersion() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Brain::Builder::setFormatVersion( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::NeuroForge::Schema::ProcessingMode Brain::Reader::getProcessingMode() const {
  return _reader.getDataField< ::NeuroForge::Schema::ProcessingMode>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::NeuroForge::Schema::ProcessingMode Brain::Builder::getProcessingMode() {
  return _builder.getDataField< ::NeuroForge::Schema::ProcessingMode>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Brain::Builder::setProcessingMode( ::NeuroForge::Schema::ProcessingMode value) {
  _builder.setDataField< ::NeuroForge::Schema::ProcessingMode>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::NeuroForge::Schema::BrainState Brain::Reader::getBrainState() const {
  return _reader.getDataField< ::NeuroForge::Schema::BrainState>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline  ::NeuroForge::Schema::BrainState Brain::Builder::getBrainState() {
  return _builder.getDataField< ::NeuroForge::Schema::BrainState>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void Brain::Builder::setBrainState( ::NeuroForge::Schema::BrainState value) {
  _builder.setDataField< ::NeuroForge::Schema::BrainState>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline float Brain::Reader::getTargetFrequency() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline float Brain::Builder::getTargetFrequency() {
  return _builder.getDataField<float>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Brain::Builder::setTargetFrequency(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t Brain::Reader::getProcessingCycles() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t Brain::Builder::getProcessingCycles() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Brain::Builder::setProcessingCycles( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline bool Brain::Reader::hasRegions() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Brain::Builder::hasRegions() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>::Reader Brain::Reader::getRegions() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>::Builder Brain::Builder::getRegions() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Brain::Builder::setRegions( ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>::Builder Brain::Builder::initRegions(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Brain::Builder::adoptRegions(
    ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>> Brain::Builder::disownRegions() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Region,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Brain::Reader::hasGlobalSynapses() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Brain::Builder::hasGlobalSynapses() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Reader Brain::Reader::getGlobalSynapses() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Builder Brain::Builder::getGlobalSynapses() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Brain::Builder::setGlobalSynapses( ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>::Builder Brain::Builder::initGlobalSynapses(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void Brain::Builder::adoptGlobalSynapses(
    ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>> Brain::Builder::disownGlobalSynapses() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::Synapse,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool Brain::Reader::hasRegionNames() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool Brain::Builder::hasRegionNames() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>::Reader Brain::Reader::getRegionNames() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>::Builder Brain::Builder::getRegionNames() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void Brain::Builder::setRegionNames( ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>::Builder Brain::Builder::initRegionNames(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void Brain::Builder::adoptRegionNames(
    ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>> Brain::Builder::disownRegionNames() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::NeuroForge::Schema::RegionNameEntry,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool Brain::Reader::hasCustomUpdateOrder() const {
  return !_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline bool Brain::Builder::hasCustomUpdateOrder() {
  return !_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader Brain::Reader::getCustomUpdateOrder() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Brain::Builder::getCustomUpdateOrder() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline void Brain::Builder::setCustomUpdateOrder( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), value);
}
inline void Brain::Builder::setCustomUpdateOrder(::kj::ArrayPtr<const  ::uint32_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Brain::Builder::initCustomUpdateOrder(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), size);
}
inline void Brain::Builder::adoptCustomUpdateOrder(
    ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> Brain::Builder::disownCustomUpdateOrder() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}

}  // namespace
}  // namespace

CAPNP_END_HEADER

